name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      squid:
        image: secsamdev/usiem-apache2
        ports:
          - 8080:80

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: CI_CD=1 cargo test --verbose
      timeout-minutes: 5